#!/bin/bash

# runs MythExpress via nvm

. /etc/default/mythexpress

cd $RUNDIR

. $NVMDIR/nvm.sh
nvm use v4

exec node $APPDIR/mythexpress.js --no-deprecation --logfile $LOGDIR/mythexpress.$(date +"%F-%H-%M-%S").log
